server:
  http:
    host: "0.0.0.0"
    port: "8080"

redis:
  address: "localhost:6379"
  password: ""

db:
  postgres:
    dialect: "postgres"
    dsn: "host=localhost port=5432 dbname=db user=db password=db sslmode=disable"
  memory:
    maxsize: 20

repository:
  type: "postgres"
